[platformio]
default_envs = wristband
src_dir = .

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM5
board_build.partitions = huge_app.csv
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    Wire
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
    me-no-dev/AsyncTCP @ ^1.1.1
    plerup/EspSoftwareSerial @ ^8.2.0
build_flags = 
    -I..

[env:wristband]
build_src_filter = +<wristband/wristband_v2.cpp> +<../MPU6050.cpp>
build_flags = -Iwristband ${env.build_flags}

[env:receiver]
build_src_filter = +<receiver/receiver_v2.cpp>
build_flags = -Ireceiver ${env.build_flags}

[env:door_reader]
build_src_filter = +<door_reader/door_reader_v2.cpp>
build_flags = -Idoor_reader ${env.build_flags}

[env:unified_node]
build_src_filter = +<unified_node/unified_node_v2.cpp>
build_flags = -Iunified_node ${env.build_flags}
